language: node_js

os:
  - linux
  - osx

node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - valgrind

notifications:
  email: false

env:
  global:
    - secure: "SFMrz/7qLPlVUN0clzthZlkILAdMoRClAggSux61wSITGvor6+jXx245muW66b1U3BoO5bjy1BwXSQwTNSc9uHfq0to9b7QwGCh04X4MDtAgcVwOCEXWkIKTZLVLkBQpxG+XPkLCwxA0Mkc8amFGEHSqn0w664UwoSqlRgUnAvg="
    - secure: "TboT8Z9uoFCb2ocvP+Srbm+rU799Fv2vJ+Za3+DcVLqG7IJyYOHUK7BNogSkbjO70+Ns2vFcDY1OZYwAbqXQ+1ah0Sh186u0PJaCyR3wTTbPdoHSNCFXLvcD82GE/NkLWurBmpDXB+3NaPgvEz3Xpy0O1Shl2bQMwW2m5NaV3eg="

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export CXX=g++-4.8;
    fi
  - npm install

script:
  - rm -rf build
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cd ..
  - cmake --build cmake-build-debug --target wrtc -- -j 2
  - ./bin/test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd cmake-build-debug;
      ctest -T memcheck;
      cd ..;
    fi
  - rm -rf cmake-build-debug
  - npm install
  - npm test
  - if [[ $TRAVIS_TAG ]] ||
       [[ `git show -s --format=%B $TRAVIS_COMMIT` == *'[publish binary]'* ]];
    then
      $RUN node_modules/.bin/node-pre-gyp package publish;
    fi
